# Writes the header that names the commit a build comes from: its short hash and its subject line.
# Run by the `app_version` target on every build, so the label is never the commit of an older
# configure. The header is replaced only when it changed, so an unchanged commit rebuilds nothing.
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<header> -P version.cmake
find_package(Git QUIET)
set(hash "unknown")
set(subject "")
if(GIT_FOUND)
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY ${SOURCE_DIR} OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    execute_process(COMMAND ${GIT_EXECUTABLE} log -1 --format=%s
        WORKING_DIRECTORY ${SOURCE_DIR} OUTPUT_VARIABLE subject OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    # Uncommitted changes: say so, since the hash then names code the build does not match.
    execute_process(COMMAND ${GIT_EXECUTABLE} status --porcelain --untracked-files=no
        WORKING_DIRECTORY ${SOURCE_DIR} OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(dirty)
        set(hash "${hash}+")
    endif()
endif()
if(NOT hash)
    set(hash "unknown")
endif()
# A C string literal: backslashes and quotes escaped.
string(REPLACE "\\" "\\\\" subject "${subject}")
string(REPLACE "\"" "\\\"" subject "${subject}")
file(WRITE "${OUTPUT}.tmp" "// Generated by cmake/version.cmake; not checked in.\n#define NV_GIT_COMMIT \"${hash}\"\n#define NV_GIT_SUBJECT \"${subject}\"\n")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
